language: scala
scala:
  - 2.12.4
jdk:
  - oraclejdk8

install:
  - pip install --user codecov

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt coverageReport
  - codecov --token=${CODECOV_KEY}
